template:
  name: Deployment
  type: Stage
  projectIdentifier: PM_Signoff
  orgIdentifier: default
  spec:
    type: Deployment
    spec:
      deploymentType: Kubernetes
      service:
        serviceRef: k8s
      environment:
        environmentRef: k8sdev
        deployToAll: false
        infrastructureDefinitions:
          - identifier: playground
      execution:
        steps:
          - step:
              name: Rollout Deployment
              identifier: rolloutDeployment
              type: K8sRollingDeploy
              timeout: 10m
              spec:
                skipDryRun: false
                pruningEnabled: false
        rollbackSteps:
          - step:
              name: Rollback Rollout Deployment
              identifier: rollbackRolloutDeployment
              type: K8sRollingRollback
              timeout: 10m
              spec:
                pruningEnabled: false
    failureStrategies:
      - onFailure:
          errors:
            - AllErrors
          action:
            type: StageRollback
    when:
      pipelineStatus: Success
  identifier: Deployment
  versionLabel: "1"
