pipeline:
    name: Forte
    identifier: Forte
    allowStageExecutions: false
    projectIdentifier: CD_Product_Team
    orgIdentifier: default
    tags: {}
    stages:
        - stage:
              name: Deploy Service API
              identifier: Deploy_Service_API
              description: ""
              type: Deployment
              spec:
                  serviceConfig:
                      serviceRef: KIGHTWING_SERVICE
                      serviceDefinition:
                          type: Kubernetes
                          spec:
                              variables: []
                              manifests:
                                  - manifest:
                                        identifier: dev
                                        type: K8sManifest
                                        spec:
                                            store:
                                                type: Github
                                                spec:
                                                    connectorRef: ProductManagementRepo
                                                    gitFetchType: Branch
                                                    paths:
                                                        - cdng/
                                                    branch: dev
                                            skipResourceVersioning: false
                              artifacts:
                                  sidecars: []
                  infrastructure:
                      environmentRef: rohandev
                      infrastructureDefinition:
                          type: KubernetesDirect
                          spec:
                              connectorRef: rohan_product_cluster
                              namespace: rohan-dev
                              releaseName: release-<+INFRA_KEY>
                      allowSimultaneousDeployments: false
                  execution:
                      steps:
                          - step:
                                type: ShellScript
                                name: print
                                identifier: print
                                spec:
                                    shell: Bash
                                    onDelegate: true
                                    source:
                                        type: Inline
                                        spec:
                                            script: |-
                                                echo <+pipeline.variables.deployment_number>
                                                echo "<+pipeline.variables.namespace>
                                    environmentVariables: []
                                    outputVariables: []
                                    executionTarget: {}
                                timeout: 10m
                                failureStrategies: []
                      rollbackSteps:
                          - step:
                                name: Rollback Rollout Deployment
                                identifier: rollbackRolloutDeployment
                                type: K8sRollingRollback
                                timeout: 10m
                                spec: {}
                  serviceDependencies: []
              tags: {}
              failureStrategies:
                  - onFailure:
                        errors:
                            - AllErrors
                        action:
                            type: StageRollback
    variables:
        - name: deployment_number
          type: String
          value: <+input>
        - name: namespace
          type: String
          value: hello+<+pipeline.variables.deployment_number>
