pipeline:
    name: Harness Demo
    identifier: Harness_Demo
    projectIdentifier: Rohan
    orgIdentifier: default
    tags: {}
    stages:
        - stage:
              name: Deploy to L3
              identifier: Deploy_to_L3
              description: ""
              type: Deployment
              spec:
                  deploymentType: Kubernetes
                  service:
                      serviceRef: publicnginx
                      serviceInputs:
                          serviceDefinition:
                              type: Kubernetes
                              spec:
                                  artifacts:
                                      primary:
                                          type: DockerRegistry
                                          spec:
                                              tag: <+input>
                  environment:
                      environmentRef: L3
                      deployToAll: false
                      infrastructureDefinitions:
                          - identifier: L3_K8s
                  execution:
                      steps:
                          - step:
                                name: Rollout Deployment
                                identifier: rolloutDeployment
                                type: K8sRollingDeploy
                                timeout: 10m
                                spec:
                                    skipDryRun: false
                          - step:
                                name: Clean up L3
                                identifier: Clean_up_L3
                                template:
                                    templateRef: Cleanup_Demo
                                    versionLabel: 0.0.1
                          - step:
                                type: ShellScript
                                name: test
                                identifier: test
                                spec:
                                    shell: Bash
                                    onDelegate: true
                                    source:
                                        type: Inline
                                        spec:
                                            script: bal
                                    environmentVariables: []
                                    outputVariables: []
                                    executionTarget: {}
                                timeout: 10m
                      rollbackSteps:
                          - step:
                                name: Rollback Rollout Deployment
                                identifier: rollbackRolloutDeployment
                                type: K8sRollingRollback
                                timeout: 10m
                                spec: {}
              tags: {}
              failureStrategies:
                  - onFailure:
                        errors:
                            - AllErrors
                        action:
                            type: StageRollback
        - stage:
              name: Deploy to L2
              identifier: Deploy_to_L2
              description: ""
              type: Deployment
              spec:
                  deploymentType: Kubernetes
                  service:
                      serviceRef: publicnginx
                      serviceInputs:
                          serviceDefinition:
                              type: Kubernetes
                              spec:
                                  artifacts:
                                      primary:
                                          type: DockerRegistry
                                          spec:
                                              tag: <+input>
                  environment:
                      environmentRef: L2
                      deployToAll: false
                      infrastructureDefinitions:
                          - identifier: L2_K8s
                  execution:
                      steps:
                          - step:
                                name: Rollout Deployment
                                identifier: rolloutDeployment
                                type: K8sRollingDeploy
                                timeout: 10m
                                spec:
                                    skipDryRun: false
                          - step:
                                name: Clean up L2
                                identifier: Clean_up_L2
                                template:
                                    templateRef: Cleanup_Demo
                                    versionLabel: 0.0.1
                          - step:
                                type: ShellScript
                                name: hello
                                identifier: hello
                                spec:
                                    shell: Bash
                                    onDelegate: true
                                    source:
                                        type: Inline
                                        spec:
                                            script: |-
                                                echo 
                                                "human"
                                    environmentVariables: []
                                    outputVariables: []
                                    executionTarget: {}
                                timeout: 10m
                      rollbackSteps:
                          - step:
                                name: Rollback Rollout Deployment
                                identifier: rollbackRolloutDeployment
                                type: K8sRollingRollback
                                timeout: 10m
                                spec: {}
              tags: {}
              failureStrategies:
                  - onFailure:
                        errors:
                            - AllErrors
                        action:
                            type: StageRollback
        - stage:
              name: Approval to Production
              identifier: Approval_to_Production
              template:
                  templateRef: Approval_to_Production
                  versionLabel: 0.0.1
        - stage:
              name: Deploy to L1
              identifier: Deploy_to_L1
              description: ""
              type: Deployment
              spec:
                  deploymentType: Kubernetes
                  service:
                      serviceRef: publicnginx
                      serviceInputs:
                          serviceDefinition:
                              type: Kubernetes
                              spec:
                                  artifacts:
                                      primary:
                                          type: DockerRegistry
                                          spec:
                                              tag: <+input>
                  environment:
                      environmentRef: L1
                      deployToAll: false
                      infrastructureDefinitions:
                          - identifier: L1_K8s
                  execution:
                      steps:
                          - stepGroup:
                                name: Canary Deployment
                                identifier: canaryDepoyment
                                steps:
                                    - step:
                                          name: Canary Deployment
                                          identifier: canaryDeployment
                                          type: K8sCanaryDeploy
                                          timeout: 10m
                                          spec:
                                              instanceSelection:
                                                  type: Count
                                                  spec:
                                                      count: 1
                                              skipDryRun: false
                                    - step:
                                          name: Canary Delete
                                          identifier: canaryDelete
                                          type: K8sCanaryDelete
                                          timeout: 10m
                                          spec: {}
                          - stepGroup:
                                name: Primary Deployment
                                identifier: primaryDepoyment
                                steps:
                                    - step:
                                          name: Rolling Deployment
                                          identifier: rollingDeployment
                                          type: K8sRollingDeploy
                                          timeout: 10m
                                          spec:
                                              skipDryRun: false
                          - step:
                                type: HarnessApproval
                                name: Cleanup Demo
                                identifier: Cleanup_Demo
                                spec:
                                    approvalMessage: Please review the following information and approve the pipeline progression
                                    includePipelineExecutionHistory: true
                                    approvers:
                                        userGroups:
                                            - account.ProductManagement
                                        minimumCount: 1
                                        disallowPipelineExecutor: false
                                    approverInputs: []
                                timeout: 1d
                          - step:
                                name: Cleanup Cluster
                                identifier: Cleanup_Cluster
                                template:
                                    templateRef: Cleanup_Demo
                                    versionLabel: 0.0.1
                      rollbackSteps:
                          - step:
                                name: Canary Delete
                                identifier: rollbackCanaryDelete
                                type: K8sCanaryDelete
                                timeout: 10m
                                spec: {}
                          - step:
                                name: Rolling Rollback
                                identifier: rollingRollback
                                type: K8sRollingRollback
                                timeout: 10m
                                spec: {}
              tags: {}
              failureStrategies:
                  - onFailure:
                        errors:
                            - AllErrors
                        action:
                            type: StageRollback
