pipeline:
  name: Kubernetes Canary
  identifier: Kubernetes_Canary
  projectIdentifier: Rohan
  orgIdentifier: default
  tags: {}
  stages:
    - stage:
        name: Canary Deployment
        identifier: Canary_Deployment
        description: ""
        type: Deployment
        spec:
          deploymentType: Kubernetes
          service:
            serviceRef: helloworldKustomize
            serviceInputs:
              serviceDefinition:
                type: Kubernetes
                spec:
                  manifests:
                    - manifest:
                        identifier: helloWorldKustomize
                        type: Kustomize
                        spec:
                          store:
                            type: Github
                            spec:
                              branch: <+input>
          execution:
            steps:
              - stepGroup:
                  name: Canary Deployment
                  identifier: canaryDepoyment
                  steps:
                    - step:
                        name: Canary Deployment
                        identifier: canaryDeployment
                        type: K8sCanaryDeploy
                        timeout: 10m
                        spec:
                          instanceSelection:
                            type: Count
                            spec:
                              count: 1
                          skipDryRun: true
                    - step:
                        name: Canary Delete
                        identifier: canaryDelete
                        type: K8sCanaryDelete
                        timeout: 10m
                        spec: {}
              - stepGroup:
                  name: Primary Deployment
                  identifier: primaryDepoyment
                  steps:
                    - step:
                        name: Rolling Deployment
                        identifier: rollingDeployment
                        type: K8sRollingDeploy
                        timeout: 10m
                        spec:
                          skipDryRun: true
                          pruningEnabled: false
                          commandFlags: []
                        failureStrategies: []
            rollbackSteps:
              - step:
                  name: Canary Delete
                  identifier: rollbackCanaryDelete
                  type: K8sCanaryDelete
                  timeout: 10m
                  spec: {}
              - step:
                  name: Rolling Rollback
                  identifier: rollingRollback
                  type: K8sRollingRollback
                  timeout: 10m
                  spec: {}
          environment:
            environmentRef: staging
            deployToAll: false
            infrastructureDefinitions:
              - identifier: productstaging
        tags: {}
        failureStrategies:
          - onFailure:
              errors:
                - AllErrors
              action:
                type: StageRollback
    - stage:
        name: Deploy to new cluster
        identifier: Deploy_to_new_cluster
        description: ""
        type: Pipeline
        spec:
          org: default
          pipeline: Golden_Pipeline
          project: Rohan
          inputs:
            identifier: Golden_Pipeline
            template:
              templateInputs:
                stages:
                  - stage:
                      identifier: Deploy
                      template:
                        templateInputs:
                          type: Deployment
                          spec:
                            service:
                              serviceRef: <+input>
                              serviceInputs: <+input>
                            environment:
                              environmentRef: <+input>
                              environmentInputs: <+input>
                              infrastructureDefinitions: <+input>
                          when:
                            condition: <+input>
