pipeline:
    name: Kustomize Pipeline
    identifier: Kustomize_Pipeline
    projectIdentifier: Continuous_Deployment_Product_Team
    orgIdentifier: Product_Management_Design
    tags: {}
    stages:
        - stage:
              name: Deploy to Dev
              identifier: Deploy_to_Dev
              description: ""
              type: Deployment
              spec:
                  serviceConfig:
                      serviceRef: helloworld
                      serviceDefinition:
                          type: Kubernetes
                          spec:
                              variables:
                                  - name: replica
                                    type: String
                                    value: "2"
                                  - name: image
                                    type: String
                                    value: harness/todolist-sample:131
                              manifests:
                                  - manifest:
                                        identifier: dev_kustomize
                                        type: Kustomize
                                        spec:
                                            store:
                                                type: Github
                                                spec:
                                                    connectorRef: ThisRohanGupta
                                                    gitFetchType: Branch
                                                    folderPath: kustomize-cdng/base/
                                                    repoName: Product-Management
                                                    branch: main
                                            pluginPath: ""
                                            skipResourceVersioning: false
                                  - manifest:
                                        identifier: dev_patch
                                        type: KustomizePatches
                                        spec:
                                            store:
                                                type: Github
                                                spec:
                                                    connectorRef: ThisRohanGupta
                                                    gitFetchType: Branch
                                                    paths:
                                                        - kustomize-cdng/patch.yaml
                                                    branch: main
                  infrastructure:
                      environmentRef: sandbox
                      infrastructureDefinition:
                          type: KubernetesDirect
                          spec:
                              connectorRef: account.k8s_staging
                              namespace: rohan-kustomize
                              releaseName: release-<+INFRA_KEY>
                      allowSimultaneousDeployments: false
                  execution:
                      steps:
                          - stepGroup:
                                name: Canary Deployment
                                identifier: canaryDepoyment
                                steps:
                                    - step:
                                          name: Canary Deployment
                                          identifier: canaryDeployment
                                          type: K8sCanaryDeploy
                                          timeout: 10m
                                          spec:
                                              instanceSelection:
                                                  type: Count
                                                  spec:
                                                      count: 1
                                              skipDryRun: false
                                    - step:
                                          name: Canary Delete
                                          identifier: canaryDelete
                                          type: K8sCanaryDelete
                                          timeout: 10m
                                          spec: {}
                                rollbackSteps:
                                    - step:
                                          name: Canary Delete
                                          identifier: rollbackCanaryDelete
                                          type: K8sCanaryDelete
                                          timeout: 10m
                                          spec: {}
                          - stepGroup:
                                name: Primary Deployment
                                identifier: primaryDepoyment
                                steps:
                                    - step:
                                          name: Rolling Deployment
                                          identifier: rollingDeployment
                                          type: K8sRollingDeploy
                                          timeout: 10m
                                          spec:
                                              skipDryRun: false
                                rollbackSteps:
                                    - step:
                                          name: Rolling Rollback
                                          identifier: rollingRollback
                                          type: K8sRollingRollback
                                          timeout: 10m
                                          spec: {}
                      rollbackSteps: []
              tags: {}
              failureStrategies:
                  - onFailure:
                        errors:
                            - AllErrors
                        action:
                            type: StageRollback
