pipeline:
  name: prod
  identifier: prod
  projectIdentifier: PM_Signoff
  orgIdentifier: default
  tags:
    prod: ""
  stages:
    - stage:
        name: prod only
        identifier: prod_only
        description: ""
        type: Deployment
        spec:
          deploymentType: Kubernetes
          service:
            serviceRef: kubernetes
            serviceInputs:
              serviceDefinition:
                type: Kubernetes
                spec:
                  artifacts:
                    primary:
                      primaryArtifactRef: prod
                      sources:
                        - identifier: prod
                          type: DockerRegistry
                          spec:
                            imagePath: library/nginx
                            digest: <+input>
                            tag: stable-perl
          execution:
            steps:
              - step:
                  type: ShellScript
                  name: ShellScript_1
                  identifier: ShellScript_1
                  spec:
                    shell: Bash
                    executionTarget: {}
                    source:
                      type: Inline
                      spec:
                        script: |+
                          echo "connector name" <+infra.connector.name>
                          echo "region" <infra.connector.region>
                          echo "deployment type" <+stage.spec.deploymentType>

                    environmentVariables: []
                    outputVariables: []
                  timeout: 10m
            rollbackSteps:
              - step:
                  name: Rollback Rollout Deployment
                  identifier: rollbackRolloutDeployment
                  type: K8sRollingRollback
                  timeout: 10m
                  spec:
                    pruningEnabled: false
          environment:
            environmentRef: k8sprod
            deployToAll: false
            infrastructureDefinitions:
              - identifier: prod
        tags: {}
        failureStrategies:
          - onFailure:
              errors:
                - AllErrors
              action:
                type: StageRollback
  allowStageExecutions: true
