pipeline:
  name: prod
  identifier: prod
  projectIdentifier: PM_Signoff
  orgIdentifier: default
  tags:
    prod: ""
  stages:
    - stage:
        name: prod only
        identifier: prod_only
        tags: {}
        template:
          templateRef: demo1
          versionLabel: "1.0"
          gitBranch: main
          templateInputs:
            type: Deployment
            spec:
              service:
                serviceInputs:
                  serviceDefinition:
                    type: Kubernetes
                    spec:
                      artifacts:
                        primary:
                          sources:
                            - identifier: prod
                              type: DockerRegistry
                              spec:
                                digest: <+input>
                      variables:
                        - name: token
                          type: String
                          value: <+input>
                        - name: password
                          type: Secret
                          value: <+input>
                        - name: cpu
                          type: Number
                          value: <+input>
  allowStageExecutions: true
