pipeline:
  name: Remote Pipeline Demo
  identifier: sony
  projectIdentifier: PM_Signoff
  orgIdentifier: default
  tags: {}
  stages:
    - stage:
        name: Deploy
        identifier: Deploy
        description: ""
        type: Deployment
        spec:
          deploymentType: NativeHelm
          service:
            serviceRef: helm
          environment:
            environmentRef: k8sdev
            deployToAll: false
            infrastructureDefinitions:
              - identifier: helmdev
                inputs:
                  identifier: helmdev
                  type: KubernetesDirect
                  spec:
                    namespace: dev
          execution:
            steps:
              - step:
                  type: K8sDryRun
                  name: Dry Run
                  identifier: Dry_Run
                  spec: {}
                  timeout: 10m
              - step:
                  name: Helm Deployment
                  identifier: helmDeployment
                  type: HelmDeploy
                  timeout: 10m
                  spec:
                    skipDryRun: false
            rollbackSteps:
              - step:
                  name: Helm Rollback
                  identifier: helmRollback
                  type: HelmRollback
                  timeout: 10m
                  spec: {}
        tags: {}
        failureStrategies:
          - onFailure:
              errors:
                - AllErrors
              action:
                type: StageRollback
    - stage:
        name: ci
        identifier: ci
        description: ""
        type: CI
        spec:
          cloneCodebase: true
          infrastructure:
            type: KubernetesDirect
            spec:
              connectorRef: <+input>
              namespace: <+input>
              automountServiceAccountToken: true
              nodeSelector: {}
              os: Linux
          execution:
            steps:
              - step:
                  type: GitClone
                  name: GitClone_1
                  identifier: GitClone_1
                  spec:
                    connectorRef: <+input>.allowedValues(ThisRohanGupta,account.Test_Github,account.Rohan_Github,account.Test123,account.ThisRohanGupta)
                    repoName: <+input>
                    cloneDirectory: <+input>
                    build:
                      type: branch
                      spec:
                        branch: main
  notificationRules:
    - name: Failure
      identifier: Failure
      pipelineEvents:
        - type: PipelineFailed
        - type: StageFailed
          forStages:
            - AllStages
        - type: StepFailed
      notificationMethod:
        type: Slack
        spec:
          userGroups:
            - account._account_all_users
          webhookUrl: ""
      enabled: true
    - name: Success
      identifier: Success
      pipelineEvents:
        - type: PipelineSuccess
        - type: StageSuccess
          forStages:
            - AllStages
      notificationMethod:
        type: Slack
        spec:
          userGroups:
            - account._account_all_users
          webhookUrl: ""
      enabled: true
    - name: Job Start Slack Notification
      identifier: Job_Start_Slack_Notification
      pipelineEvents:
        - type: PipelineStart
      notificationMethod:
        type: Slack
        spec:
          userGroups:
            - account._account_all_users
          webhookUrl: ""
      enabled: true
  properties:
    ci:
      codebase:
        connectorRef: <+input>
        repoName: <+input>
        build: <+input>
