apiVersion: apps/v1
kind: Deployment
metadata:
  name: rohan-helloworld
  namespace: rohan-dev
  labels:
    app: rohan-helloworld
  annotations:
spec:
  selector:
    matchLabels:
      app: rohan-helloworld
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: rohan-helloworld
    spec:
      containers:
      - name: rohan-helloworld
        image: harness/todolist-sample:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 5000
