pipeline:
  name: Approval
  identifier: Approval
  projectIdentifier: PM_Signoff
  orgIdentifier: default
  tags: {}
  stages:
    - stage:
        name: Approval
        identifier: Approval
        description: ""
        type: Approval
        spec:
          execution:
            steps:
              - step:
                  name: Harness Approval
                  identifier: Harness_Approval
                  type: HarnessApproval
                  timeout: 1d
                  spec:
                    approvalMessage: |-
                      Please review the following information
                      and approve the pipeline progression
                    includePipelineExecutionHistory: true
                    approvers:
                      minimumCount: 1
                      disallowPipelineExecutor: false
                      userGroups: <+input>
                    isAutoRejectEnabled: false
                    approverInputs:
                      - name: Name
                        defaultValue: <+input>.allowedValues("name1","name2").executionInput()
                      - name: ID
                        defaultValue: <+input>.allowedValues("name1","name2").executionInput()
                      - name: Test
                        defaultValue: <+input>.allowedValues("name1","name2").executionInput()
        tags: {}
        variables:
          - name: name
            type: String
            description: ""
            required: false
            value: <+input>.allowedValues(name1,name2,name3)
          - name: approver_id
            type: String
            description: ""
            required: false
            value: <+input>.allowedValues(id1,id2,id3)
          - name: test
            type: String
            description: ""
            required: false
            value: <+input>
