pipeline:
    name: cd-deployment
    identifier: cddeployment
    allowStageExecutions: false
    projectIdentifier: Continuous_Deployment_Product_Team
    orgIdentifier: Product_Management_Design
    tags: {}
    stages:
        - stage:
              name: Deploy
              identifier: Deploy
              template:
                  templateRef: Demo_Stage
                  versionLabel: v1
                  templateInputs:
                      type: Deployment
                      spec:
                          serviceConfig:
                              serviceDefinition:
                                  type: Kubernetes
                                  spec:
                                      manifests:
                                          - manifest:
                                                identifier: dev
                                                type: K8sManifest
                                                spec:
                                                    store:
                                                        type: Github
                                                        spec:
                                                            branch: <+input>
                                      artifacts:
                                          primary:
                                              type: DockerRegistry
                                              spec:
                                                  tag: <+input>
                          infrastructure:
                              environmentRef: <+input>
