pipeline:
    name: cd-deployment
    identifier: cddeployment
    allowStageExecutions: false
    projectIdentifier: Continuous_Deployment_Product_Team
    orgIdentifier: Product_Management_Design
    tags: {}
    stages:
        - stage:
              name: CD Demo
              identifier: CD_Demo
              template:
                  templateRef: CD_Demo
                  templateInputs:
                      type: Deployment
                      spec:
                          serviceConfig:
                              serviceDefinition:
                                  type: Kubernetes
                                  spec:
                                      artifacts:
                                          primary:
                                              type: DockerRegistry
                                              spec:
                                                  tag: <+input>
        - stage:
              name: CD Demo
              identifier: CD_Demo_1
              template:
                  templateRef: CD_Demo
                  templateInputs:
                      type: Deployment
                      spec:
                          serviceConfig:
                              serviceDefinition:
                                  type: Kubernetes
                                  spec:
                                      artifacts:
                                          primary:
                                              type: DockerRegistry
                                              spec:
                                                  tag: <+input>
