pipeline:
    name: cd-deployment
    identifier: cddeployment
    allowStageExecutions: false
    projectIdentifier: Continuous_Deployment_Product_Team
    orgIdentifier: Product_Management_Design
    tags: {}
    stages:
        - stage:
              name: CD Deploy
              identifier: CD_Deploy
              description: ""
              type: Deployment
              spec:
                  serviceConfig:
                      serviceRef: helloworld
                      serviceDefinition:
                          type: Kubernetes
                          spec:
                              variables:
                                  - name: nab_variable
                                    type: Number
                                    value: <+input>
                              manifests:
                                  - manifest:
                                        identifier: dev_manifest
                                        type: K8sManifest
                                        spec:
                                            store:
                                                type: Github
                                                spec:
                                                    connectorRef: ThisRohanGupta_Repo
                                                    gitFetchType: Branch
                                                    paths:
                                                        - cdng/
                                                    branch: main
                                            skipResourceVersioning: false
                              artifacts:
                                  primary:
                                      spec:
                                          connectorRef: account.Rohan_Dockerhub
                                          imagePath: library/nginx
                                          tag: <+input>
                                      type: DockerRegistry
                  infrastructure:
                      environmentRef: development
                      infrastructureDefinition:
                          type: KubernetesDirect
                          spec:
                              connectorRef: gkeautopilot
                              namespace: dev
                              releaseName: release-<+INFRA_KEY>
                      allowSimultaneousDeployments: false
                  execution:
                      steps:
                          - step:
                                type: ShellScript
                                name: test
                                identifier: test
                                spec:
                                    shell: Bash
                                    onDelegate: true
                                    source:
                                        type: Inline
                                        spec:
                                            script: echo <+serviceConfig.serviceDefinition.spec.variables.nab_variable>
                                    environmentVariables: []
                                    outputVariables: []
                                    executionTarget: {}
                                timeout: 10m
                      rollbackSteps:
                          - step:
                                name: Rollback Rollout Deployment
                                identifier: rollbackRolloutDeployment
                                type: K8sRollingRollback
                                timeout: 10m
                                spec: {}
                  serviceDependencies: []
              tags: {}
              failureStrategies:
                  - onFailure:
                        errors:
                            - AllErrors
                        action:
                            type: StageRollback
