pipeline:
  name: Charter
  identifier: Charter
  projectIdentifier: Rohan
  orgIdentifier: default
  tags: {}
  stages:
    - stage:
        name: WIN-Release-Primary-validation
        identifier: WINReleasePrimaryvalidation
        description: ""
        type: Deployment
        spec:
          deploymentType: NativeHelm
          service:
            serviceRef: <+input>
            serviceInputs: <+input>
          environment:
            environmentRef: <+input>
            deployToAll: false
            environmentInputs: <+input>
            infrastructureDefinitions: <+input>
          execution:
            steps:
              - step:
                  type: ShellScript
                  name: Set_PrePrimary_Value
                  identifier: Set_PrePrimary_Value
                  spec:
                    shell: Bash
                    onDelegate: true
                    source:
                      type: Inline
                      spec:
                        script: |-
                          PRIMARY_WEIGHT=""
                          CANARY_WEIGHT=""
                          CANARY_DEPLOY_MODE=""

                          env=`echo ${infra.name} | sed -e "s/-canary//g"`

                          enable_canary_deploy="false"

                          if [[  (${workflow.variables.ENABLE_CANARY_INT} == "true" &&  $env == 'int' ) || ( ${workflow.variables.ENABLE_CANARY_PERF} == "true" &&  $env == 'perf') || ( ${workflow.variables.ENABLE_CANARY_STAGE} == "true" &&  $env == 'stage') || ( ${workflow.variables.ENABLE_CANARY_PROD} == "true" &&  $env == 'prod')  ]]; then

                               enable_canary_deploy="true"
                          fi

                          if [[ $enable_canary_deploy == "true" ]]; then
                             export PRIMARY_WEIGHT="0"
                             export CANARY_WEIGHT="100"
                             export CANARY_DEPLOY_MODE="true"
                          else
                             export PRIMARY_WEIGHT="100"
                             export CANARY_WEIGHT="0"
                             export CANARY_DEPLOY_MODE="false"
                          fi

                          #export PRIMARY_WEIGHT="100"
                          #export CANARY_WEIGHT="0"

                          echo "PRIMARY_WEIGHT Value"
                          echo ${PRIMARY_WEIGHT}

                          echo "CANARY_WEIGHT Value"
                          echo ${CANARY_WEIGHT}

                          echo "CANARY_DEPLOY_MODE Value"
                          echo ${CANARY_DEPLOY_MODE}

                          export INFRA_NAME=`echo ${infra.name} | sed -e "s/-canary//g"`

                          echo "INFRA NAME"
                          echo ${INFRA_NAME}
                    environmentVariables: []
                    outputVariables:
                      - name: CANARY_WEIGHT
                        type: String
                        value: CANARY_WEIGHT
                      - name: PRIMARY_WEIGHT
                        type: String
                        value: PRIMARY_WEIGHT
                      - name: INFRA_NAME
                        type: String
                        value: INFRA_NAME
                      - name: CANARY_DEPLOY_MODE
                        type: String
                        value: CANARY_DEPLOY_MODE
                  timeout: 10m
              - step:
                  name: Fetch_EWS_Creds
                  identifier: Fetch_EWS_Creds
                  template:
                    templateRef: Fetch_EWS_Creds
              - step:
                  type: ShellScript
                  name: Publish Helm Chart Version
                  identifier: Publish_Helm_Chart_Version
                  spec:
                    shell: Bash
                    onDelegate: true
                    source:
                      type: Inline
                      spec:
                        script: |-
                          VERSION=""
                          RELEASE_VERSION=""
                          gitURL=https://${secrets.getValue("scp-harness-gitlab-user")}:${secrets.getValue("scp-harness-gitlab-password")}@gitlab.se-charter.net/scp/${workflow.variables.SUB_GROUP}/${workflow.variables.PROJECT}/${workflow.variables.GIT_REPO}.git

                          if [ -z "${workflow.variables.CHART_VERSION}" ] && [ -z "${workflow.variables.GIT_BRANCH_NAME}" ]; then
                             echo "Please specify either a chart version or branch name"
                          exit 1
                          fi  

                          if [ -z "${workflow.variables.CHART_VERSION}" ]; then
                             branchExists=$(git ls-remote --heads $gitURL  | wc -l)
                            if [ "${branchExists}" = "0" ]; then
                              echo "Could not find branch ${workflow.variables.GIT_BRANCH_NAME} please specify a branch that exists"
                              exit 1
                            fi
                            rm -rf ${workflow.variables.GIT_REPO}

                            git clone --single-branch --branch ${workflow.variables.GIT_BRANCH_NAME} $gitURL

                            apt-get install -y software-properties-common
                            add-apt-repository -y ppa:rmescandon/yq
                            apt-get install -y yq

                            cd ${workflow.variables.GIT_REPO}
                            
                            # CHART_VERSION=$(yq r Chart.yaml version)
                            #test=$(yq r Chart.yaml version)
                            #VERSION=$(yq r Chart.yaml version)
                            test=$(yq e '.version' Chart.yaml )
                            VERSION=$(yq e '.version' Chart.yaml )
                          else
                            VERSION=${workflow.variables.CHART_VERSION}
                          fi



                          if [ -z "$VERSION" ]; then
                            echo "Did not find a chart version please review if this is the correct release branch ${workflow.variables.GIT_BRANCH_NAME} or specify chart version"
                            exit 1
                          fi

                          export CHART_VERSION=${VERSION}
                          export RELEASE_VERSION=$(echo ${VERSION} | cut -f1,2 -d.)
                          echo "Chart Version"
                          echo ${VERSION}
                          echo "Release Version"
                          echo $RELEASE_VERSION
                    environmentVariables: []
                    outputVariables:
                      - name: CHART_VERSION
                        type: String
                        value: CHART_VERSION
                      - name: RELEASE_VERSION
                        type: String
                        value: RELEASE_VERSION
                  timeout: 10m
              - step:
                  name: Helm Deployment
                  identifier: helmDeployment
                  type: HelmDeploy
                  timeout: 10m
                  spec:
                    skipDryRun: false
            rollbackSteps:
              - step:
                  name: Helm Rollback
                  identifier: helmRollback
                  type: HelmRollback
                  timeout: 10m
                  spec: {}
        tags: {}
        failureStrategies:
          - onFailure:
              errors:
                - AllErrors
              action:
                type: StageRollback
