pipeline:
  name: K8s Helm CD Pipeline
  identifier: K8s_Helm_CD_Pipeline
  projectIdentifier: Rohan
  orgIdentifier: default
  tags: {}
  stages:
    - stage:
        name: Deploy Chart
        identifier: Deploy_Chart
        template:
          templateRef: Rolling_Deployment_Dev
          versionLabel: 0.0.1
          templateInputs:
            type: Deployment
            spec:
              service:
                serviceRef: <+input>
                serviceInputs: <+input>
  variables:
    - name: releaseName
      type: String
      description: ""
      value: <+input>
