pipeline:
  name: K8s Helm CD Pipeline
  identifier: K8s_Helm_CD_Pipeline
  projectIdentifier: Rohan
  orgIdentifier: default
  tags: {}
  stages:
    - stage:
        name: Deploy
        identifier: Deploy
        template:
          templateRef: CD_Stage_Charter
          versionLabel: 1.0.0
          templateInputs:
            type: Deployment
            spec:
              environment:
                environmentRef: <+input>
                environmentInputs: <+input>
                serviceOverrideInputs: <+input>
                infrastructureDefinitions: <+input>
