name: rohan-demo
replicas: 1
image: <+pipeline.stages.Build_Service_API.variables.api_image>
sidecar1: <+pipeline.stages.Deploy_Service_API.spec.serviceConfig.serviceDefinition.spec.artifacts.sidecars.dev.spec.imagePath>
sidecar2: <+pipeline.stages.Deploy_Service_API.spec.serviceConfig.serviceDefinition.spec.artifacts.sidecars.proxy.spec.imagePath>
sidecar3: <+pipeline.stages.Deploy_Service_API.spec.serviceConfig.serviceDefinition.spec.artifacts.primary.spec.imagePath>


createNamespace: true
namespace: <+infra.namespace>

# Service Type allow you to specify what kind of service you want.
# Possible values for ServiceType are:
# ClusterIP | NodePort | LoadBalancer | ExternalName
serviceType: LoadBalancer

# A Service can map an incoming port to any targetPort.
# targetPort is where application is listening on inside the container.
servicePort: 80
serviceTargetPort: 80

env:
  config:
    key1: harnessDemo
  secrets:
    key2: sandbox
