apiVersion: apps/v1
kind: Deployment
metadata:
 name: example-deploy
 namespace: default
spec:
 template :
   spec:
     containers:
       - name: example-app
         image: <+serviceConfig.serviceDefinition.spec.variables.image>
 
---
apiVersion: apps/v1
kind: Deployment
metadata:
 name: example-deploy
 namespace: default
spec:
 replicas: <+serviceConfig.serviceDefinition.spec.variables.replica>
