apiVersion: apps/v1
kind: Deployment
metadata:
 name: rohan-helloworld
 namespace: sandbox
spec:
 template :
   spec:
     containers:
       - name: rohan-helloworld
         image: <+serviceConfig.serviceDefinition.spec.variables.image>
 
---
apiVersion: apps/v1
kind: Deployment
metadata:
 name: rohan-helloworld
 namespace: sandbox
spec:
 replicas: <+serviceConfig.serviceDefinition.spec.variables.replica>
