name: <+serviceVariable.name>
host: <+serviceVariable.host>
image: <+artifact.image>
canaryName: <+serviceVariable.canaryName>
stableName: <+serviceVariable.stableName>
endpoint: color
canaryEndpoint: color-canary
stableEndpoint: color-stable
splitTraffic: false

replicas: 2
namespace: <+infra.namespace>

frontend:
  title: Nginx - Canary Traffic Shift
  loadBalancer: http://<+serviceVariable.host>
  ui: nginx-canary
  image: us.gcr.io/sales-209522/continuous-requests:110
