name: ${serviceVariable.name}
host: ${serviceVariable.host}
image: ${artifact.metadata.image}
stageName: ${serviceVariable.stageName}
primaryName: ${serviceVariable.primaryName}
endpoint: color-bg
stageEndpoint: color-bg-stage
primaryEndpoint: color-bg-primary
splitTraffic: false

replicas: 2
namespace: ${infra.kubernetes.namespace}

frontend:
  title: Nginx - Blue/Green Traffic Shift
  loadBalancer: http://${serviceVariable.host}
  uiPath: ${serviceVariable.uiPath}
  image: us.gcr.io/sales-209522/continuous-requests:110
